Ticari Otomasyon/Models/Classes/Kategori.cs
using System;
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations;
using System.Linq;
using System.Web;

namespace Ticari_Otomasyon.Models.Classes
{
    public class Kategori
    {
        [Key]
        public int Id { get; set; }

        [StringLength(50)]
        public string KategoriAdi { get; set; }
        public ICollection<Urun> Uruns { get; set; }
    }
}

Ticari Otomasyon/Controllers/KategoriController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;
using System.Web.Mvc;
using Ticari_Otomasyon.Models.Classes;
using PagedList;
using PagedList.Mvc;


namespace Ticari_Otomasyon.Controllers
{
    public class KategoriController : Controller
    {
        // GET: Kategori
        Context c = new Context();
        public ActionResult Index(int sayfa=1)
        {
            var degerler = c.Kategoris.ToList().ToPagedList(sayfa,5);
            return View(degerler);
        }

        [HttpGet]
        public ActionResult KategoriEkle()
        {
            return View();
        }
        [HttpPost]
        public ActionResult KategoriEkle(Kategori kategori)
        {
            c.Kategoris.Add(kategori);
            c.SaveChanges();
            return RedirectToAction("Index");

        }

        public ActionResult KategoriSil(int id)
        {
            var ktg = c.Kategoris.Find(id);
            c.Kategoris.Remove(ktg);
            c.SaveChanges();
            return RedirectToAction("Index");

        }

        public ActionResult KategoriGetir(int id)
        {
            var ktg = c.Kategoris.Find(id);
            return View("KategoriGetir", ktg);
        }

        public ActionResult KategoriGuncelle(Kategori kategori)
        {
            var ktg = c.Kategoris.Find(kategori.Id);
            ktg.KategoriAdi = kategori.KategoriAdi;
            c.SaveChanges();
            return RedirectToAction("Index");
        }

        public ActionResult Deneme()
        {
            Cascading cs = new Cascading();
            cs.Kategoriler = new SelectList(c.Kategoris, "Id", "KategoriAdi");
            cs.Urunler = new SelectList(c.Uruns, "Id", "Ad");
            return View(cs);
        }

        public JsonResult UrunGetir(int p)
        {
            var urunlistesi = (from x in c.Uruns
                               join y in c.Kategoris
                               on x.Kategori.Id equals y.Id
                               where x.Kategori.Id == p
                               select new
                               {
                                   Text = x.Ad,
                                   Value = x.Id.ToString()
                               }).ToList();

            return Json(urunlistesi, JsonRequestBehavior.AllowGet);
        }
    }
}

Ticari Otomasyon/Views/Kategori/Deneme.cshtml
@model Ticari_Otomasyon.Models.Classes.Cascading
@{
    ViewBag.Title = "Deneme";
    Layout = "~/Views/Shared/AdminLayout.cshtml";
}

<script src="~/Scripts/jquery-3.4.1.min.js"></script>

<script>

    $(function () {

        $('#DrpKategori').change(function () {

            var id = $('#DrpKategori').val();

            $.ajax({

                url: '/Kategori/UrunGetir',

                data: { p: id },

                type: "POST",

                dataType: "Json",

                success: function (data) {

                    console.log(data);

                    $('#DrpUrun').empty();

                    for (var i = 0; i < data.length; i++) {

                        $('#DrpUrun').append("<option value='" + data[i].Value + "'>" + data[i].Text + "</Option>");

                    }

                }

            });

        });

    });

</script>



<br />
<div>
    <h2>Kategoriler - Ürünler</h2>
</div>
<br />
<div>
    @Html.Label("Kategoriler")
    @Html.DropDownList("DrpKategori", Model.Kategoriler, "---Kategori Seçiniz---", new
    {
    @class = "form-control"
    })
    <br />
    @Html.Label("Ürünler")
    @Html.DropDownList("DrpUrun", Model.Urunler, "---Ürün Seçiniz---", new
    {
    @class = "form-control"
    })
</div>

Ticari Otomasyon/Views/Kategori/Index.cshtml
@using Ticari_Otomasyon.Models.Classes
@using PagedList
@using PagedList.Mvc
@model PagedList.IPagedList<Kategori>

@{
    ViewBag.Title = "Index";

    Layout = "~/Views/Shared/AdminLayout.cshtml";

}



<table class="table table-bordered" style="margin-top:20px;">
    <tr>

        <th>#</th>
        <th>Kategori Adı</th>
        <th>Sil</th>
        <th>Güncelle</th>


    </tr>
    @foreach (var k in Model)
    {

        <tr>
            <th>
                @k.Id
            </th>
            <td>

                @k.KategoriAdi
            </td>
            <td><a href="/Kategori/KategoriSil/@k.Id" class="btn btn-danger">Sil</a></td>
            <td><a href="/Kategori/KategoriGetir/@k.Id" class="btn  btn-warning">Güncelle</a></td>

        </tr>
    }
</table>
<br />

@Html.PagedListPager((IPagedList)Model, sayfa => Url.Action("Index", new { sayfa }), new PagedListRenderOptions
{

    LiElementClasses = new List<string>
    { "page-link"}
})


<a href="/Kategori/KategoriEkle" class="btn btn-dark">Kategori Ekle</a>

Ticari Otomasyon/Views/Kategori/KategoriEkle.cshtml
@model Ticari_Otomasyon.Models.Classes.Kategori
@{
    ViewBag.Title = "KategoriEkle";
    Layout = "~/Views/Shared/AdminLayout.cshtml";
}
<script src="~/Scripts/jquery-3.4.1.js"></script>
<br />
<h2>Yeni Kategori Sayfası</h2>
<br />
<form class="form-group" method="post">
    @Html.LabelFor(x=>x.KategoriAdi)
    @Html.TextBoxFor(x=>x.KategoriAdi,new {@class="form-control"})

    <br />
    <button class="btn btn-warning" id="Btn1">Kaydet</button>
    <script>
        $('#Btn1').click(function (){
            alert("Kategori başarılı bir şekilde eklendi. ")
        });
    </script>
</form>

Ticari Otomasyon/Views/Kategori/KategoriGetir.cshtml
@model Ticari_Otomasyon.Models.Classes.Kategori
@{
    ViewBag.Title = "KategoriGetir";
    Layout = "~/Views/Shared/AdminLayout.cshtml";
}

<br />
<h2>Kategori Güncelleme</h2>
<br />

@using (Html.BeginForm("KategoriGuncelle", "Kategori", FormMethod.Post))
{
    <div class="form-group">
        @Html.LabelFor(x => x.KategoriAdi)
        @Html.TextBoxFor(x => x.KategoriAdi, new { @class = "form-control" })
        @Html.HiddenFor(x => x.Id)
    </div>
    <button class="btn btn-warning">Güncelle</button>
}