Ticari Otomasyon/Controllers/FaturaController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;
using System.Web.Mvc;
using Ticari_Otomasyon.Models.Classes;

namespace Ticari_Otomasyon.Controllers
{
    public class FaturaController : Controller
    {
        // GET: Fatura
        Context c = new Context();
        public ActionResult Index()
        {
            var liste = c.Faturas.ToList();
            return View(liste);
        }

        [HttpGet]
        public ActionResult FaturaEkle()
        {
            return View();
        }

        [HttpPost]
        public ActionResult FaturaEkle(Fatura f)
        {
            c.Faturas.Add(f);
            c.SaveChanges();
            return View();
        }

        public ActionResult FaturaGetir(int id)
        {
            var fatura = c.Faturas.Find(id);
            return View("FaturaGetir", fatura);

        }

        public ActionResult FaturaGuncelle(Fatura f)
        {
            var fatura = c.Faturas.Find(f.Id);
            fatura.SeriNo = f.SeriNo;
            fatura.SiraNo = f.SiraNo;
            fatura.Saat = f.Saat;
            fatura.Tarih = f.Tarih;
            fatura.TeslimAlan = f.TeslimAlan;
            fatura.TeslimEden = f.TeslimEden;
            fatura.VergiDairesi = f.VergiDairesi;
            c.SaveChanges();
            return RedirectToAction("Index");
        }

        public ActionResult FaturaDetay(int id)
        {

            var fatura = c.FaturaKalems.Where(x => x.FaturaId == id).ToList();
            var ftr = c.Faturas.Where(x => x.Id == id).Select(y => y.SeriNo + " " + y.SiraNo).FirstOrDefault();
            ViewBag.ftrs = ftr;
            return View(fatura);

        }


        [HttpGet]
        public ActionResult YeniKalem()
        {
            return View();
        }

      
        public ActionResult YeniKalem(FaturaKalem p)
        {
            c.FaturaKalems.Add(p);
            c.SaveChanges();
            return RedirectToAction("Index");

        }

        public ActionResult Dinamik()
        {
            Dinamik d = new Dinamik();
            d.deger1 = c.Faturas.ToList();
            d.deger2 = c.FaturaKalems.ToList();
            return View(d);
        }

        public ActionResult FaturaKaydet(string SeriNo, string SiraNo, DateTime Tarih, string VergiDairesi,
            string Saat, string TeslimEden, string TeslimAlan, string Toplam, FaturaKalem[] kalemler)
        {
            Fatura f = new Fatura();
            f.SeriNo = SeriNo;
            f.SiraNo = SiraNo;
            f.Tarih = Tarih;
            f.VergiDairesi = VergiDairesi;
            f.Saat = Saat;
            f.TeslimEden = TeslimEden;
            f.TeslimAlan = TeslimAlan;
            f.Toplam = decimal.Parse(Toplam);
            c.Faturas.Add(f);
            foreach (var x in kalemler)
            {
                FaturaKalem fk = new FaturaKalem();
                fk.Aciklama = x.Aciklama;
                fk.BirimFiyat = x.BirimFiyat;
                fk.FaturaId = x.Id;
                fk.Miktar = x.Miktar;
                fk.Tutar = x.Tutar;
                c.FaturaKalems.Add(fk);
            }
            c.SaveChanges();
            return Json("İşlem Başarılı", JsonRequestBehavior.AllowGet);
        }
    }
}

Ticari Otomasyon/Views/Shared/AdminLayout.cshtml
@{
    Layout = null;
}

<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="utf-8" />
    <meta http-equiv="X-UA-Compatible" content="IE=edge" />
    <meta name="viewport" content="width=device-width, initial-scale=1, shrink-to-fit=no" />
    <meta name="description" content="" />
    <meta name="author" content="" />
    <title>MVC5 ile Online Ticari Otomasyon</title>
    <link href="~/Web/dist/css/styles.css" rel="stylesheet" />
    <script src="https://cdnjs.cloudflare.com/ajax/libs/font-awesome/5.15.1/js/all.min.js" crossorigin="anonymous"></script>
</head>
<body>
    <nav class="sb-topnav navbar navbar-expand navbar-dark bg-dark">
        <a class="navbar-brand" href="index.html">Ticari Otomasyon</a>
        <button class="btn btn-link btn-sm order-1 order-lg-0" id="sidebarToggle" href="#"><i class="fas fa-bars"></i></button>
        <!-- Navbar Search-->
        <form class="d-none d-md-inline-block form-inline ml-auto mr-0 mr-md-3 my-2 my-md-0">
            <div class="input-group">
                <input class="form-control" type="text" placeholder="Aranacak Kelimeyi Giriniz" aria-label="Search" aria-describedby="basic-addon2" />
                <div class="input-group-append">
                    <button class="btn btn-primary" type="button"><i class="fas fa-search"></i></button>
                </div>
            </div>
        </form>
        <!-- Navbar-->
        <ul class="navbar-nav ml-auto ml-md-0">
            <li class="nav-item dropdown">
                <a class="nav-link dropdown-toggle" id="userDropdown" href="#" role="button" data-toggle="dropdown" aria-haspopup="true" aria-expanded="false"><i class="fas fa-user fa-fw"></i></a>
                <div class="dropdown-menu dropdown-menu-right" aria-labelledby="userDropdown">
                    <a class="dropdown-item" href="#">Ayarlar</a>
                    <a class="dropdown-item" href="#">Hesabım</a>
                    <a class="dropdown-item" href="#">Mesajlar</a>
                    <div class="dropdown-divider"></div>
                    <a class="dropdown-item" href="#">Çıkış Yap</a>
                </div>
            </li>
        </ul>
    </nav>
    <div id="layoutSidenav">
        <div id="layoutSidenav_nav">
            <nav class="sb-sidenav accordion sb-sidenav-dark" id="sidenavAccordion">
                <div class="sb-sidenav-menu">
                    <div class="nav">
                        <div class="sb-sidenav-menu-heading">İşlemler</div>
                        <a class="nav-link" href="/Kategori/Index">
                            <div class="sb-nav-link-icon"><i class="fas fa-tachometer-alt"></i></div>
                            Kategoriler
                        </a>
                        <a class="nav-link" href="/Urun/Index/">
                            <div class="sb-nav-link-icon"><i class="fas fa-flask"></i></div>
                            Ürünler
                        </a>
                        <a class="nav-link" href="/Departman/Index/">
                            <div class="sb-nav-link-icon"><i class="fas fa-bars"></i></div>
                            Departmanlar
                        </a>
                        <a class="nav-link" href="/Cari/Index">
                            <div class="sb-nav-link-icon"><i class="fas fa-users"></i></div>
                            Cariler
                        </a>
                        <a class="nav-link" href="/Personel/Index/">
                            <div class="sb-nav-link-icon"><i class="fas fa-street-view"></i></div>
                            Personeller
                        </a>


                        <a class="nav-link" href="/Harita/Index/">
                            <div class="sb-nav-link-icon"><i class="fas fa-street-view"></i></div>
                            Harita
                        </a>


                        <div class="sb-sidenav-menu-heading">Raport & Fatura</div>
                        <a class="nav-link" href="/Satis/Index/">
                            <div class="sb-nav-link-icon"><i class="fas fa-taxi"></i></div>
                            Satışlar
                        </a>
                        <a class="nav-link" href="/Fatura/Index">
                            <div class="sb-nav-link-icon"><i class="fas fa-calendar"></i></div>
                            Faturalar
                        </a>




                        <a class="nav-link" href="/Kargo/Index/">
                            <div class="sb-nav-link-icon"><i class="fas fa-gift"></i></div>
                            Kargolar
                        </a>
                        <a class="nav-link" href="/Urun/UrunListesi">
                            <div class="sb-nav-link-icon"><i class="fas fa-print"></i></div>
                            Pdf ~ Excel
                        </a>
                        <a class="nav-link" href="/Istatistik/Index">
                            <div class="sb-nav-link-icon"><i class="fas fa-chart-pie"></i></div>
                            İstatistikler
                        </a>
                        <a class="nav-link" href="/Galeri/Index">
                            <div class="sb-nav-link-icon"><i class="fas fa-camera-retro"></i></div>
                            Galeri
                        </a>
                        <a class="nav-link" href="/QR/Index">
                            <div class="sb-nav-link-icon"><i class="fas fa-university"></i></div>
                            QR Kod
                        </a>
                        <a class="nav-link" href="/istatistik/KolayTablolar">
                            <div class="sb-nav-link-icon"><i class="fas fa-brain"></i></div>
                            Hızlı Bakış
                        </a>


                    </div>
                </div>
                <div class="sb-sidenav-footer">
                    <div class="small">Logged in as:</div>
                    Start Bootstrap
                </div>
            </nav>
        </div>
        <div id="layoutSidenav_content">
            <main>
                <div class="container-fluid">
                    @RenderBody()
                </div>
            </main>
            <footer class="py-4 bg-light mt-auto">
                <div class="container-fluid">
                    <div class="d-flex align-items-center justify-content-between small">
                        <div class="text-muted">Copyright &copy; Your Website 2020</div>
                        <div>
                            <a href="#">Privacy Policy</a>
                            &middot;
                            <a href="#">Terms &amp; Conditions</a>
                        </div>
                    </div>
                </div>
            </footer>
        </div>
    </div>
    <script src="https://code.jquery.com/jquery-3.5.1.slim.min.js" crossorigin="anonymous"></script>
    <script src="https://cdn.jsdelivr.net/npm/bootstrap@4.5.3/dist/js/bootstrap.bundle.min.js" crossorigin="anonymous"></script>
    <script src="~/Web/dist/js/scripts.js"></script>
</body>
</html>

Ticari Otomasyon/Views/Shared/_CariLayout.cshtml
@{
    Layout = null;
}

<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="utf-8" />
    <meta http-equiv="X-UA-Compatible" content="IE=edge" />
    <meta name="viewport" content="width=device-width, initial-scale=1, shrink-to-fit=no" />
    <meta name="description" content="" />
    <meta name="author" content="" />
    <title>MVC5 ile Online Ticari Otomasyon</title>
    <link href="~/Web/dist/css/styles.css" rel="stylesheet" />
    <script src="https://cdnjs.cloudflare.com/ajax/libs/font-awesome/5.15.1/js/all.min.js" crossorigin="anonymous"></script>
</head>
<body>
    <nav class="sb-topnav navbar navbar-expand navbar-dark bg-dark">
        <a class="navbar-brand" href="index.html">Ticari Otomasyon</a>
        <button class="btn btn-link btn-sm order-1 order-lg-0" id="sidebarToggle" href="#"><i class="fas fa-bars"></i></button>
        <!-- Navbar Search-->
        <form class="d-none d-md-inline-block form-inline ml-auto mr-0 mr-md-3 my-2 my-md-0">
            <div class="input-group">
                <input class="form-control" type="text" placeholder="Aranacak Kelimeyi Giriniz" aria-label="Search" aria-describedby="basic-addon2" />
                <div class="input-group-append">
                    <button class="btn btn-primary" type="button"><i class="fas fa-search"></i></button>
                </div>
            </div>
        </form>
        <!-- Navbar-->
        <ul class="navbar-nav ml-auto ml-md-0">
            <li class="nav-item dropdown">
                <a class="nav-link dropdown-toggle" id="userDropdown" href="#" role="button" data-toggle="dropdown" aria-haspopup="true" aria-expanded="false"><i class="fas fa-user fa-fw"></i></a>
                <div class="dropdown-menu dropdown-menu-right" aria-labelledby="userDropdown">
                    <a class="dropdown-item" href="#">Ayarlar</a>
                    <a class="dropdown-item" href="#">Yardım</a>
                    <div class="dropdown-divider"></div>
                    <a class="dropdown-item" href="/CariPanel/LogOut/">Çıkış Yap</a>
                </div>
            </li>
        </ul>
    </nav>
    <div id="layoutSidenav">
        <div id="layoutSidenav_nav">
            <nav class="sb-sidenav accordion sb-sidenav-dark" id="sidenavAccordion">
                <div class="sb-sidenav-menu">
                    <div class="nav">
                        <div class="sb-sidenav-menu-heading">Cari Panel Menüsü</div>
                        <a class="nav-link" href="/CariPanel/Index">
                            <div class="sb-nav-link-icon"><i class="fas fa-person-booth"></i></div>
                            Profilim
                        </a>
                        <a class="nav-link" href="/CariPanel/Siparislerim/">
                            <div class="sb-nav-link-icon"><i class="fas fa-box"></i></div>
                            Siparişlerim
                        </a>
                        <a class="nav-link" href="/CariPanel/KargoTakip/">
                            <div class="sb-nav-link-icon"><i class="fas fa-truck"></i></div>
                            Kargo takibi
                        </a>
                        <a class="nav-link" href="/CariPanel/GelenMesajlar">
                            <div class="sb-nav-link-icon"><i class="fas fa-mail-bulk"></i></div>
                            Mesajlar
                        </a>
                        <a class="nav-link" href="/CariPanel/LogOut/">
                            <div class="sb-nav-link-icon"><i class="fas fa-sign-out-alt"></i></div>
                            Çıkış Yap
                        </a>



                    </div>
                </div>

            </nav>
        </div>
        <div id="layoutSidenav_content">
            <main>
                <div class="container-fluid">
                    @RenderBody()
                </div>
            </main>

        </div>
    </div>
    <script src="https://code.jquery.com/jquery-3.5.1.slim.min.js" crossorigin="anonymous"></script>
    <script src="https://cdn.jsdelivr.net/npm/bootstrap@4.5.3/dist/js/bootstrap.bundle.min.js" crossorigin="anonymous"></script>
    <script src="~/Web/dist/js/scripts.js"></script>
</body>
</html>

Ticari Otomasyon/Views/Shared/_Layout.cshtml
<!DOCTYPE html>
<html>
<head>
    <meta charset="utf-8" />
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>@ViewBag.Title</title>
    @Styles.Render("~/Content/css")
    @Scripts.Render("~/bundles/modernizr")
</head>
<body>
    <div class="navbar navbar-inverse navbar-fixed-top">
        <div class="container">
            <div class="navbar-header">
                <button type="button" class="navbar-toggle" data-toggle="collapse" data-target=".navbar-collapse">
                    <span class="icon-bar"></span>
                    <span class="icon-bar"></span>
                    <span class="icon-bar"></span>
                </button>
                @Html.ActionLink("Fatura İşlemleri", "Dinamik", "Fatura", new { area = "" }, new { @class = "navbar-brand" })
            </div>
            <div class="navbar-collapse collapse">
                <ul class="nav navbar-nav">
                    <li>@Html.ActionLink("Faturalar", "Dinamik", "Fatura")</li>
                    <li>@Html.ActionLink("Yardım", "About", "Home")</li>
                    <li>@Html.ActionLink("İletişim", "Contact", "Home")</li>
                </ul>
            </div>
        </div>
    </div>
    <div class="container body-content">
        @RenderBody()
        <hr />
        <footer>
            <p>&copy; @DateTime.Now.Year </p>
        </footer>
    </div>

    @Scripts.Render("~/bundles/jquery")
    @Scripts.Render("~/bundles/bootstrap")
    @RenderSection("scripts", required: false)
</body>
</html>