Ticari Otomasyon/Models/Classes/Cari.cs
using System;
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations;
using System.Linq;
using System.Web;

namespace Ticari_Otomasyon.Models.Classes
{
    public class Cari
    {
        [Key]
        public int Id { get; set; }

        [StringLength(50,ErrorMessage ="Lütfen en fazla 50 karakter giriniz.")]
        [Required(ErrorMessage = "Bu alanı boş geçemezsiniz!")]
        public string Ad { get; set; }

        [StringLength(50)]
        public string Soyad { get; set; }

        [StringLength(20)]
        public string Sehir { get; set; }

        [StringLength(20)]
        public string Meslek { get; set; }

        [StringLength(100)]
        public string Mail { get; set; }

       
        [StringLength(20)]
        public string Sifre { get; set; }

        [StringLength(20)]
        public string Telefon { get; set; }
        public bool Durum { get; set; }

        [StringLength(50)]
        public string CariGorseli { get; set; }
        public ICollection<SatisHareket> SatisHarekets { get; set; }
    }
}

Ticari Otomasyon/Controllers/CariController.cs
using System;
using System.Collections.Generic;
using System.IO;
using System.Linq;
using System.Web;
using System.Web.Mvc;
using Ticari_Otomasyon.Models.Classes;

namespace Ticari_Otomasyon.Controllers
{
    public class CariController : Controller
    {
        // GET: Cari
        Context c = new Context();
        public ActionResult Index()
        {
            var deger = c.Caris.Where(x => x.Durum == true).ToList();
            return View(deger);
        }
        [HttpGet]
        public ActionResult YeniCari()
        {
            return View();
            
        }

        [HttpPost]
        public ActionResult YeniCari(Cari p)
        {
            p.Durum = true;
            c.Caris.Add(p);
            c.SaveChanges();
            return RedirectToAction("Index");
        }


        public ActionResult CariSil(int id) 
        {

            var p = c.Caris.Find(id);
            p.Durum = false;
            c.SaveChanges();
            return RedirectToAction("Index");
        }

        public ActionResult CariGetir(int id )
        {
            var cari = c.Caris.Find(id);
            return View("CariGetir", cari);
        }
        public ActionResult CariGuncelle(Cari p)
        {
            if (!ModelState.IsValid)
            {
                return View("CariGetir");
            }
            var cari = c.Caris.Find(p.Id);
            cari.Ad = p.Ad;
            cari.Soyad = p.Soyad;
            cari.Sehir = p.Sehir;
            cari.Mail = p.Mail;
            c.SaveChanges();
            return RedirectToAction("Index");
        }

        public ActionResult MusteriSatis(int id)
        {
            var degerler = c.SatisHarekets.Where(x => x.CariId == id).ToList();
            var cr = c.Caris.Where(x => x.Id == id).Select(y => y.Ad + " " + y.Soyad).FirstOrDefault();
            ViewBag.cari = cr;
            return View(degerler);

        }

    }
}

Ticari Otomasyon/Views/Cari/CariGetir.cshtml
@model Ticari_Otomasyon.Models.Classes.Cari
@{
    ViewBag.Title = "CariGetir";
    Layout = "~/Views/Shared/AdminLayout.cshtml";
}

<h2>Cari Güncelleme Sayfası</h2>
<br />
@using (Html.BeginForm("CariGuncelle", "Cari", FormMethod.Post))
{

    @Html.HiddenFor(x => x.Id)
    @Html.LabelFor(x => x.Ad)
    @Html.TextBoxFor(x => x.Ad, new { @class = "form-control" })
    @Html.ValidationMessageFor(x => x.Ad, "", new { @style = "color:red" })
    <br />
    @Html.LabelFor(x => x.Soyad)
    @Html.TextBoxFor(x => x.Soyad, new { @class = "form-control" })
    <br />
    @Html.LabelFor(x => x.Sehir)
    @Html.TextBoxFor(x => x.Sehir, new { @class = "form-control" })
    <br />
    @Html.LabelFor(x => x.Mail)
    @Html.TextBoxFor(x => x.Mail, new { @class = "form-control" })
    <br />
    @Html.LabelFor(x => x.Meslek)
    @Html.TextBoxFor(x => x.Meslek, new { @class = "form-control" })
    <br />
    @Html.LabelFor(x => x.Telefon)
    @Html.TextBoxFor(x => x.Telefon, new { @class = "form-control" })
<br />
    <button class="btn btn-warning">Güncelle</button>
}

Ticari Otomasyon/Views/Cari/Index.cshtml
@using Ticari_Otomasyon.Models.Classes
@model List<Cari>
@{
    ViewBag.Title = "Index";
    Layout = "~/Views/Shared/AdminLayout.cshtml";
}

<br />
<table class="table table-striped">
    <tr>

        <th>Cari Kodu </th>
        <th>Ad</th>
        <th>Soyad</th>
        <th>Şehir</th>
        <th>Mail</th>
        <th>Meslek</th>
        <th>Şehir</th>
        <th>Telefon</th>
        <th>Sil</th>
        <th>Güncelle</th>
        <th>Detay</th>


    </tr>
    @foreach (var k in Model)
    {

        <tr>
            <td>@k.Id</td>
            <td> @k.Ad</td>
            <td> @k.Soyad</td>
            <td> @k.Sehir</td>
            <td> @k.Mail</td>
            <td> @k.Meslek</td>
            <td> @k.Sehir</td>
            <td> @k.Telefon</td>
            

            <td><a href="/Cari/CariSil/@k.Id" class="btn btn-danger">Sil</a></td>
            <td><a href="/Cari/CariGetir/@k.Id" class="btn  btn-warning">Güncelle</a></td>
            <td><a href="/Cari/MusteriSatis/@k.Id" class=" btn btn-default" style="background-color:lightseagreen">Satış Geçmişi</a></td>

        </tr>
    }
</table>
<br />
<a href="/Cari/YeniCari/" class="btn btn-dark">Cari Ekle</a>

Ticari Otomasyon/Views/Cari/MusteriSatis.cshtml
@using Ticari_Otomasyon.Models.Classes
@model List<SatisHareket>
@{
    ViewBag.Title = "MusteriSatis";
    Layout = "~/Views/Shared/AdminLayout.cshtml";
}

<br />
<ol class="breadcrumb mb-4">
    <li class="breadcrumb-item active">Cari Adı: @ViewBag.cari</li>
</ol>
<table class=" table table-condensed">
    <tr>
        <th>Satış Id</th>
        <th>Ürün</th>
        <th>Personel</th>
        <th>Fiyat</th>
        <th>Adet</th>
        <th>Toplam</th>
        <th>Tarih</th>
        <th>Yazdır</th>

    </tr>

    @foreach (var x in Model)
    {
        <tr>
            <td>@x.SatisId</td>
            <td>@x.Urun.Ad</td>
            <td>@x.Personel.Ad @x.Personel.Soyad</td>
            <td>@x.Fiyat</td>
            <td>@x.Adet</td>
            <td>@x.ToplamTutar</td>
            <td>@x.Tarih</td>
            <td><a href="#" class="btn btn-default" style="background-color:dodgerblue">Yazdır</a></td>
        </tr>
    }
    </table>

Ticari Otomasyon/Views/Cari/YeniCari.cshtml
@model Ticari_Otomasyon.Models.Classes.Cari
   @{
    ViewBag.Title = "YeniCari";
    Layout = "~/Views/Shared/AdminLayout.cshtml";
}

<h2>Yeni Cari Sayfası</h2>
<br />
<form class="form-group" method="post">
    @Html.LabelFor(x => x.Ad)
    @Html.TextBoxFor(x => x.Ad, new { @class = "form-control" })
    <br />
    @Html.LabelFor(x => x.Soyad)
    @Html.TextBoxFor(x => x.Soyad, new { @class = "form-control" })
    <br />
    @Html.LabelFor(x => x.Sehir)
    @Html.TextBoxFor(x => x.Sehir, new { @class = "form-control" })
    <br />
    @Html.LabelFor(x => x.Mail)
    @Html.TextBoxFor(x => x.Mail, new { @class = "form-control" })
    <br />
    @Html.LabelFor(x => x.CariGorseli)
    <br />
    <input type="file" name="CariGorseli" />
    <br />
    <button class="btn btn-default" style="background-color:greenyellow">Kaydet</button>
</form>