Ticari Otomasyon/Models/Classes/KargoTakip.cs
using System;
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations;
using System.ComponentModel.DataAnnotations.Schema;
using System.Linq;
using System.Web;

namespace Ticari_Otomasyon.Models.Classes
{
    public class KargoTakip
    {
        [Key]
        public int KargoTakipid { get; set; }

        [Column(TypeName = "Varchar")]
        [StringLength(10)]
        public string TakipKodu { get; set; }

        [Column(TypeName = "Varchar")]
        [StringLength(100)]
        public string Aciklama { get; set; }
        public DateTime TarihZaman { get; set; }

    }
}

Ticari Otomasyon/Controllers/CariPanelController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;
using System.Web.Mvc;
using System.Web.Security;
using Ticari_Otomasyon.Models.Classes;

namespace Ticari_Otomasyon.Controllers
{
    public class CariPanelController : Controller
    {
        // GET: CariPanel
        Context c = new Context();

        [Authorize]
        public ActionResult Index()
        {
            var mail = (string)Session["Mail"];
            var values = c.Mesajs.Where(x => x.Alıcı== mail).ToList();
            ViewBag.m = mail;
            var mailid = c.Caris.Where(x => x.Mail == mail).Select(y => y.Id).FirstOrDefault();
            ViewBag.mid = mailid;
            var toplamsatis = c.SatisHarekets.Where(x => x.CariId == mailid).Count();
            ViewBag.toplamsatis = toplamsatis;
            var toplamtutar = c.SatisHarekets.Where(x => x.CariId == mailid).Sum(y => (decimal?)y.ToplamTutar);
            ViewBag.toplamtutar = toplamtutar;
            var toplamurunsayisi = c.SatisHarekets.Where(x => x.CariId == mailid).Sum(y => (decimal?)y.Adet);
            ViewBag.toplamurunsayisi = toplamurunsayisi;
            var adsoyad = c.Caris.Where(x => x.Mail == mail).Select(y => y.Ad + " " + y.Soyad).FirstOrDefault();
            ViewBag.adsoyad = adsoyad;
            var meslek = c.Caris.Where(x => x.Mail == mail).Select(y => y.Meslek).FirstOrDefault();
            ViewBag.meslek = meslek;
            var sehir = c.Caris.Where(x => x.Mail == mail).Select(y => y.Sehir).FirstOrDefault();
            ViewBag.sehir = sehir;
            var telefon = c.Caris.Where(x => x.Mail == mail).Select(y => y.Telefon).FirstOrDefault();
            ViewBag.telefon = telefon;   

            return View(values);
        }

        public ActionResult Siparislerim()
        {
            var mail = (string)Session["Mail"];
            var id = c.Caris.Where(x => x.Mail == mail.ToString()).Select(y => y.Id).FirstOrDefault();
            var degerler = c.SatisHarekets.Where(x => x.CariId == id).ToList();
            return View(degerler);
        }

        public ActionResult GelenMesajlar()
        {
            var mail = (string)Session["Mail"];
            var mesajlar = c.Mesajs.Where(x => x.Alıcı == mail).OrderByDescending(x => x.MesajId).ToList();
            var gelensayisi = c.Mesajs.Count(x => x.Alıcı == mail).ToString();
            ViewBag.d1 = gelensayisi;
            var gidensayisi = c.Mesajs.Count(x => x.Gönderici == mail).ToString();
            ViewBag.d2 = gidensayisi;
            return View(mesajlar);
        }

        public ActionResult GidenMesajlar()
        {
            var mail = (string)Session["Mail"];
            var mesajlar = c.Mesajs.Where(x => x.Gönderici == mail).OrderByDescending(x => x.MesajId).ToList();
            var gelensayisi = c.Mesajs.Count(x => x.Alıcı == mail).ToString();
            ViewBag.d1 = gelensayisi;
            var gidensayisi = c.Mesajs.Count(x => x.Gönderici == mail).ToString();
            ViewBag.d2 = gidensayisi;
            return View(mesajlar);
        }

        public ActionResult MesajDetay(int id)
        {
            var degerler = c.Mesajs.Where(x => x.MesajId == id).ToList();
            var mail = (string)Session["Mail"];
            var gelensayisi = c.Mesajs.Count(x => x.Alıcı == mail).ToString();
            ViewBag.d1 = gelensayisi;
            var gidensayisi = c.Mesajs.Count(x => x.Gönderici == mail).ToString();
            ViewBag.d2 = gidensayisi;
            return View(degerler);
        }


        [HttpGet]
        public ActionResult YeniMesaj()
        {
            var mail = (string)Session["Mail"];
            var gelensayisi = c.Mesajs.Count(x => x.Alıcı == mail).ToString();
            ViewBag.d1 = gelensayisi;
            var gidensayisi = c.Mesajs.Count(x => x.Gönderici == mail).ToString();
            ViewBag.d2 = gidensayisi;

            return View();
        }

        [HttpPost]
        public ActionResult YeniMesaj(Mesaj m)
        {
            var mail = (string)Session["Mail"];
            m.Tarih = DateTime.Parse(DateTime.Now.ToShortDateString());
            m.Gönderici = mail;
            c.Mesajs.Add(m);
            c.SaveChanges();
            return View();
        }

        public ActionResult KargoTakip(string p)
        {
            var k = from x in c.KargoDetays select x;

            k = k.Where(y => y.TakipKodu.Contains(p));

            return View(k.ToList());
        }

        public ActionResult CariKargoTakip(string id)
        {
            var degerler = c.KargoTakips.Where(x => x.TakipKodu == id).ToList();
            return View(degerler);
        }
        public ActionResult LogOut()
        {
            FormsAuthentication.SignOut();
            Session.Abandon();
            return RedirectToAction("Index", "Login");
        }

        public PartialViewResult Partial1()
        {
            var mail = (string)Session["Mail"];
            var id = c.Caris.Where(x => x.Mail == mail).Select(y => y.Id).FirstOrDefault();
            var caribul = c.Caris.Find(id);
            return PartialView("Partial1",caribul);
        }

        public PartialViewResult Partial2()
        {
            var veriler = c.Mesajs.Where(x => x.Gönderici == "admin").ToList();
            return PartialView(veriler);
        }

        public ActionResult CariBilgiGuncelle(Cari cr)
        {
            var cari = c.Caris.Find(cr.Id);
            cari.Ad = cr.Ad;
            cari.Soyad = cr.Soyad;
            cari.Sifre = cr.Sifre;
            c.SaveChanges();
            return RedirectToAction("Index");
        }
    }
}

Ticari Otomasyon/Views/CariPanel/CariKargoTakip.cshtml
@using Ticari_Otomasyon.Models.Classes
@model List<KargoTakip>

@{
    ViewBag.Title = "CariKargoTakip";
    Layout = "~/Views/Shared/_CariLayout.cshtml";
}

<br />
<table class="table table-striped">
    <tr>
        <th>Açıklama</th>
        <th>Tarih</th>


    </tr>
    @foreach (var x in Model)
    {
        <tr>
            <td>@x.Aciklama</td>
            <td>@x.TarihZaman</td>

        </tr>
    }
</table>

Ticari Otomasyon/Views/CariPanel/Index.cshtml
@using Ticari_Otomasyon.Models.Classes
@model List<Mesaj>


@{
    ViewBag.Title = "Index";
    Layout = "~/Views/Shared/_CariLayout.cshtml";
}

<!DOCTYPE html>

<html>

<head>

    <meta charset="utf-8">

    <meta http-equiv="X-UA-Compatible" content="IE=edge">

    <title>AdminLTE 3 | User Profile</title>

    <!-- Tell the browser to be responsive to screen width -->

    <meta name="viewport" content="width=device-width, initial-scale=1">

    <!-- Font Awesome -->

    <link rel="stylesheet" href="~/AdminLTE-3.0.4/plugins/fontawesome-free/css/all.min.css">

    <!-- Ionicons -->

    <link rel="stylesheet" href="https://code.ionicframework.com/ionicons/2.0.1/css/ionicons.min.css">

    <!-- Theme style -->

    <link rel="stylesheet" href="~/AdminLTE-3.0.4/dist/css/adminlte.min.css">

    <!-- Google Font: Source Sans Pro -->

    <link href="https://fonts.googleapis.com/css?family=Source+Sans+Pro:300,400,400i,700" rel="stylesheet">

</head>

<body class="hold-transition sidebar-mini">

    <div class="wrapper">

        <!-- Navbar -->
        <!-- /.navbar -->
        <!-- Content Wrapper. Contains page content -->
        <!-- Content Header (Page header) -->

        <section class="content-header">

            <div class="container-fluid">

                <div class="row mb-2">

                    <div class="col-sm-6">

                        <h1>Profilim</h1>

                    </div>



                </div>

            </div><!-- /.container-fluid -->

        </section>

        <!-- Main content -->

        <section class="content">

            <div class="container-fluid">

                <div class="row">

                    <div class="col-md-3">

                        <!-- Profile Image -->

                        <div class="card card-primary card-outline">

                            <div class="card-body box-profile">

                                <div class="text-center">

                                    <img class="profile-user-img img-fluid img-circle"
                                         
                                    src="~/Images/indir (1).png"
                                    alt="User profile picture">

                                </div>
                               
                                
                                    <h3 class="profile-username text-center">@ViewBag.adsoyad</h3>

                                    <p class="text-muted text-center">@ViewBag.m</p>
                                
                                <ul class="list-group list-group-unbordered mb-3">

                                    <li class="list-group-item">

                                        <b>Toplam Satış:</b> <a class="float-right">@ViewBag.toplamsatis</a>

                                    </li>

                                    <li class="list-group-item">

                                        <b>Toplam Satış Tutarı : </b> <a class="float-right">@ViewBag.toplamtutar</a>

                                    </li>

                                    <li class="list-group-item">

                                        <b>Toplam Ürün Sayısı : </b> <a class="float-right">@ViewBag.toplamurunsayisi</a>

                                    </li>

                                </ul>

                                <a href="/CariPanel/KargoTakip/" class="btn btn-primary btn-block"><b>Kargo Takibi</b></a>

                            </div>

                            <!-- /.card-body -->

                        </div>

                        <!-- /.card -->
                        <!-- About Me Box -->

                        <div class="card card-primary">

                            <div class="card-header">

                                <h3 class="card-title">Hakkımda</h3>

                            </div>

                            <!-- /.card-header -->

                            <div class="card-body">
                             
                                
                                    <strong><i class="fas fa-book mr-1"></i> Meslek</strong>

                                    <p class="text-muted">

                                        @ViewBag.meslek
                                    </p>
                                
                                <hr>
                                  <strong><i class="fas fa-map-marker-alt mr-1"></i> Şehir</strong>

                                    <p class="text-muted">@ViewBag.sehir</p>

                                    <hr>
                                
                              
                                    <strong><i class="fas fa-pencil-alt mr-1"></i>Telefon</strong>
                                    <p class="text-muted">@ViewBag.telefon</p>
                                    
                                
                               
                            </div>

                            <!-- /.card-body -->

                        </div>

                        <!-- /.card -->

                    </div>

                    <!-- /.col -->

                    <div class="col-md-9">

                        <div class="card">

                            <div class="card-header p-2">

                                <ul class="nav nav-pills">

                                    <li class="nav-item"><a class="nav-link active" href="#activity" data-toggle="tab">Mesajlar</a></li>

                                    <li class="nav-item"><a class="nav-link" href="#timeline" data-toggle="tab">Duyurular</a></li>

                                    <li class="nav-item"><a class="nav-link" href="#settings" data-toggle="tab">Ayarlar</a></li>

                                </ul>

                            </div><!-- /.card-header -->
                            
                            <div class="card-body">

                                <div class="tab-content">

                                    <div class="active tab-pane" id="activity">

                                        <!-- Post -->
                                        @foreach (var c in Model)
                                        {
                                            <div class="post">

                                                <div class="user-block">

                                                    <img class="img-circle img-bordered-sm"
                                                    src="~/Images/indir (1).png" alt="user image">

                                                    <span class="username">

                                                        <a href="#">@c.Gönderici</a>

                                                        <a href="#" class="float-right btn-tool"><i class="fas fa-times"></i></a>

                                                    </span>

                                                    <span class="description">@c.Konu - @c.Tarih</span>

                                                </div>

                                                <!-- /.user-block -->

                                                <p>

                                                   @c.icerik

                                                </p>

                                              

                                            </div>
                                        }

                                            <!-- /.post -->
                                            <!-- Post -->

                                            <div class="post clearfix">



                                                <!-- /.user-block -->



                                                

                                            </div>

                                            <!-- /.post -->
                                            <!-- Post -->


                                            <!-- /.post -->

                                        </div>

                                    <!-- /.tab-pane -->

                                    <div class="tab-pane" id="timeline">

                                        <!-- The timeline -->

                                        @Html.Action("Partial2", "CariPanel")
                                    </div>

                                    <!-- /.tab-pane -->

                                    <div class="tab-pane" id="settings">

                                        @Html.Action("Partial1","CariPanel")

                                    </div>

                                    <!-- /.tab-pane -->

                                </div>

                                <!-- /.tab-content -->

                            </div><!-- /.card-body -->

                        </div>

                        <!-- /.nav-tabs-custom -->

                    </div>

                    <!-- /.col -->

                </div>

                <!-- /.row -->

            </div><!-- /.container-fluid -->

        </section>

        <!-- /.content -->

    </div>

    <!-- /.content-wrapper -->

    <footer class="main-footer">

        <div class="float-right d-none d-sm-block">

            <b>Version</b> 3.0.4

        </div>

        <strong>Copyright &copy; 2014-2019 <a href="http://adminlte.io">AdminLTE.io</a>.</strong> All rights

        reserved.

    </footer>

    <!-- Control Sidebar -->

    <aside class="control-sidebar control-sidebar-dark">

        <!-- Control sidebar content goes here -->

    </aside>

    <!-- /.control-sidebar -->
    <!-- ./wrapper -->
    <!-- jQuery -->

    <script src="~/AdminLTE-3.0.4/plugins/jquery/jquery.min.js"></script>

    <!-- Bootstrap 4 -->

    <script src="~/AdminLTE-3.0.4/plugins/bootstrap/js/bootstrap.bundle.min.js"></script>

    <!-- AdminLTE App -->

    <script src="~/AdminLTE-3.0.4/dist/js/adminlte.min.js"></script>

    <!-- AdminLTE for demo purposes -->

    <script src="~/AdminLTE-3.0.4/dist/js/demo.js"></script>

</body>

</html>

Ticari Otomasyon/Views/CariPanel/KargoTakip.cshtml
@using Ticari_Otomasyon.Models.Classes
@model List<KargoDetay>

@{
    ViewBag.Title = "KargoTakip";
    Layout = "~/Views/Shared/_CariLayout.cshtml";
}

<h2>Kargo Takip Ekranı</h2>

<br />

@using (Html.BeginForm("KargoTakip", "CariPanel", FormMethod.Get))
{

    <p>
        Kargo Takip Numarası: @Html.TextBox("p")
        <input type="submit" value="Ara" />
    </p>

}


<table class="table table-bordered" style="margin-top:20px;">
    <tr>

        <th>Personel</th>
        <th>Alıcı</th>
        <th>Takip Kodu</th>
        <th>Tarih </th>
        <th>Detaylar</th>

    </tr>
    @foreach (var k in Model)
    {

        <tr>
            <td>
                @k.Personel
            </td>
            <td>
                @k.Alici
            </td>
            <td>
                @k.TakipKodu
            </td>
            <td>
                @k.Tarih
            </td>
            <td><a href="/CariPanel/CariKargoTakip/@k.TakipKodu" class="btn btn-danger">Detaylar</a></td>
        </tr>
    }
</table>

<br />

Ticari Otomasyon/Views/CariPanel/Partial1.cshtml
@model Ticari_Otomasyon.Models.Classes.Cari

@using (Html.BeginForm("CariBilgiGuncelle","CariPanel",FormMethod.Post)) { 
<form class="form-horizontal">
    @Html.HiddenFor(x=>x.Id)
    <div class="form-group row">

        <label for="inputName" class="col-sm-2 col-form-label">Ad</label>

        <div class="col-sm-10">

          @Html.TextBoxFor(x=>x.Ad,new { @class = "form-control" })

        </div>

    </div>

    <div class="form-group row">

        <label for="inputEmail" class="col-sm-2 col-form-label">Soyad</label>

        <div class="col-sm-10">

            @Html.TextBoxFor(x=>x.Soyad,new { @class = "form-control" })

        </div>

    </div>

    <div class="form-group row">

        <label for="inputName2" class="col-sm-2 col-form-label">Mail</label>

        <div class="col-sm-10">

           @Html.TextBoxFor(x=>x.Mail,new { @class = "form-control" })

        </div>

    </div>

    <div class="form-group row">

        <label for="inputExperience" class="col-sm-2 col-form-label">Şehir</label>

        <div class="col-sm-10">

            @Html.TextBoxFor(x=>x.Sehir,new { @class = "form-control" })

        </div>

    </div>

    <div class="form-group row">

        <label for="inputSkills" class="col-sm-2 col-form-label">Şifre</label>

        <div class="col-sm-10">

            @Html.TextBoxFor(x=>x.Sifre,new { @class = "form-control" })

        </div>

    </div>

    <div class="form-group row">

        <div class="offset-sm-2 col-sm-10">

            <div class="checkbox">

                <label>

                    <input type="checkbox">Şifremi değiştirmek istiyorum. <a href="#"></a>

                </label>

            </div>

        </div>

    </div>

    <div class="form-group row">

        <div class="offset-sm-2 col-sm-10">

            <button type="submit" class="btn btn-danger">Güncelle</button>

        </div>

    </div>

</form>
}

Ticari Otomasyon/Views/CariPanel/Partial2.cshtml
@using Ticari_Otomasyon.Models.Classes
@model List<Mesaj>

@foreach (var c in Model)
{
    <div class="timeline timeline-inverse">

        <!-- timeline time label -->

        <div class="time-label">

            <span class="bg-warning">

                @c.Tarih.ToShortDateString()

            </span>

        </div>

        <!-- /.timeline-label -->
        <!-- timeline item -->

        <div>

            <i class="fas fa-envelope bg-primary"></i>

            <div class="timeline-item">


                <h3 class="timeline-header"><a href="#">@c.Konu</a></h3>

                <div class="timeline-body">

                   @c.icerik

                </div>

                

            </div>

        </div>

    </div>

}

Ticari Otomasyon/Views/CariPanel/Siparislerim.cshtml
@using Ticari_Otomasyon.Models.Classes
@model List<SatisHareket>
@{
    ViewBag.Title = "Siparislerim";
    Layout = "~/Views/Shared/_CariLayout.cshtml";
}

<br />
<h2>Sipariş Geçmişim</h2>
<br />

<table class=" table table-bordered ">
    <tr>
        <th>Ürün adı</th>
        <th>Fiyat</th>
        <th>Tarih</th>
    </tr>
    @foreach (var x in Model)
    {
        <tr>

            <td>@x.Urun.Ad</td>
            <td>@x.Fiyat</td>
            <td>@Convert.ToDateTime(x.Tarih).ToString("dd/MM/yyyy")</td>
        </tr>
    }
</table>

Ticari Otomasyon/Views/CariPanel/YeniMesaj.cshtml
@model Ticari_Otomasyon.Models.Classes.Mesaj
@{

    ViewBag.Title = "YeniMesaj";

    Layout = "~/Views/Shared/_CariLayout.cshtml";

}


<!DOCTYPE html>

<html>

<head>

    <meta charset="utf-8">

    <meta http-equiv="X-UA-Compatible" content="IE=edge">

    <title>AdminLTE 3 | Compose Message</title>

    <!-- Tell the browser to be responsive to screen width -->

    <meta name="viewport" content="width=device-width, initial-scale=1">

    <!-- Font Awesome -->

    <link rel="stylesheet" href="~/AdminLTE-3.0.4/plugins/fontawesome-free/css/all.min.css">

    <!-- Ionicons -->

    <link rel="stylesheet" href="https://code.ionicframework.com/ionicons/2.0.1/css/ionicons.min.css">

    <!-- Theme style -->

    <link rel="stylesheet" href="~/AdminLTE-3.0.4/dist/css/adminlte.min.css">

    <!-- summernote -->

    <link rel="stylesheet" href="~/AdminLTE-3.0.4/plugins/summernote/summernote-bs4.css">

    <!-- Google Font: Source Sans Pro -->

    <link href="https://fonts.googleapis.com/css?family=Source+Sans+Pro:300,400,400i,700" rel="stylesheet">

</head>

<body class="hold-transition sidebar-mini">





    <!-- Content Header (Page header) -->

    <section class="content-header">

        <div class="container-fluid">

            <div class="row mb-2">

                <div class="col-sm-6">

                    <h1>Yeni Mesaj Oluştur</h1>

                </div>



            </div>

        </div><!-- /.container-fluid -->

    </section>

    <!-- Main content -->

    <section class="content">

        <div class="container-fluid">

            <div class="row">

                <div class="col-md-3">

                    <a href="/CariPanel/GelenMesajlar/" class="btn btn-primary btn-block mb-3">Gelen Kutusu</a>

                    <div class="card">

                        <div class="card-header">

                            <h3 class="card-title">Klasörler</h3>

                            <div class="card-tools">

                                <button type="button" class="btn btn-tool" data-card-widget="collapse">

                                    <i class="fas fa-minus"></i>

                                </button>

                            </div>

                        </div>

                        <div class="card-body p-0">

                            <ul class="nav nav-pills flex-column">

                                <li class="nav-item active">

                                    <a href="/CariPanel/GelenMesajlar/" class="nav-link">

                                        <i class="fas fa-inbox"></i> Gelen Kutusu

                                        <span class="badge bg-primary float-right">@ViewBag.d1</span>

                                    </a>

                                </li>

                                <li class="nav-item">

                                    <a href="/CariPanel/GidenMesajlar/" class="nav-link">

                                        <i class="far fa-envelope"></i> Gönderdiğim Mesajlar
                                        <span class="badge bg-danger float-right">@ViewBag.d2</span>

                                    </a>

                                </li>

                                <li class="nav-item">

                                    <a href="#" class="nav-link">

                                        <i class="far fa-file-alt"></i> Taslaklar
                                        <span class="badge bg-fuchsia float-right">0</span>

                                    </a>

                                </li>

                                <li class="nav-item">

                                    <a href="#" class="nav-link">

                                        <i class="fas fa-filter"></i> Önemsiz Mesajlar

                                        <span class="badge bg-warning float-right">7</span>

                                    </a>

                                </li>

                                <li class="nav-item">

                                    <a href="#" class="nav-link">

                                        <i class="far fa-trash-alt"></i> Çöp Kutusu
                                        <span class="badge bg-gradient-cyan float-right">1</span>

                                    </a>

                                </li>

                            </ul>

                        </div>

                        <!-- /.card-body -->

                    </div>

                    <!-- /.card -->

                    <div class="card">

                        <div class="card-header">

                            <h3 class="card-title">Filtreler</h3>

                            <div class="card-tools">

                                <button type="button" class="btn btn-tool" data-card-widget="collapse">

                                    <i class="fas fa-minus"></i>

                                </button>

                            </div>

                        </div>

                        <div class="card-body p-0">

                            <ul class="nav nav-pills flex-column">

                                <li class="nav-item">

                                    <a href="#" class="nav-link">

                                        <i class="far fa-circle text-danger"></i>

                                        Önemliler

                                    </a>

                                </li>

                                <li class="nav-item">

                                    <a href="#" class="nav-link">

                                        <i class="far fa-circle text-warning"></i> Promosyonlar

                                    </a>

                                </li>

                                <li class="nav-item">

                                    <a href="#" class="nav-link">

                                        <i class="far fa-circle text-primary"></i>

                                        Sosyal Medya Mesajları

                                    </a>

                                </li>

                            </ul>

                        </div>

                        <!-- /.card-body -->

                    </div>

                    <!-- /.card -->

                </div>

                <!-- /.col -->

                <div class="col-md-9">

                    <div class="card card-primary card-outline">

                        <div class="card-header">

                            <h3 class="card-title">Mesaj Yaz</h3>

                        </div>

                        <!-- /.card-header -->
                        <form class="form-group" method="post">
                            <div class="card-body">

                                <div class="form-group">

                                    <input class="form-control" name="Alıcı" placeholder="Kime:">

                                </div>

                                <div class="form-group">

                                    <input class="form-control" name="Konu" placeholder="Konu:">

                                </div>

                                <div class="form-group">

                                    <textarea id="compose-textarea" name="icerik" class="form-control" style="height: 300px">

                                

                    </textarea>

                                </div>
                                <button type="submit" class="btn btn-primary"><i class="far fa-envelope"></i> Gönder</button>
                                <div class="form-group">


                                </div>
                                </div>
                        </form>
                    </div>
                       

                        <!-- /.card-body -->

                        <div class="card-footer">

                            <div class="float-right">

                                <button type="button" class="btn btn-default"><i class="fas fa-pencil-alt"></i> Taslak</button>



                            </div>

                            <button type="reset" class="btn btn-default"><i class="fas fa-times"></i> Vazgeç</button>

                        </div>

                        <!-- /.card-footer -->

                    </div>

                    <!-- /.card -->

                </div>

                <!-- /.col -->

            </div>

            <!-- /.row -->

    </section>

    <!-- /.content -->
    <!-- ./wrapper -->
    <!-- jQuery -->

    <script src="~/AdminLTE-3.0.4/plugins/jquery/jquery.min.js"></script>

    <!-- Bootstrap 4 -->

    <script src="~/AdminLTE-3.0.4/bootstrap/js/bootstrap.bundle.min.js"></script>

    <!-- AdminLTE App -->

    <script src="~/AdminLTE-3.0.4/dist/js/adminlte.min.js"></script>

    <!-- AdminLTE for demo purposes -->

    <script src="~/AdminLTE-3.0.4/dist/js/demo.js"></script>

    <!-- Summernote -->

    <script src="~/AdminLTE-3.0.4/plugins/summernote/summernote-bs4.min.js"></script>

    <!-- Page Script -->

    <script>
        $(function () {
            //Add text editor
            $('#compose-textarea').summernote()
        })</script>

</body>

</html>